
server:
  port: 8090

antivirus:
  url: http://localhost:3310

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: heslo
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  flyway:
    enabled: true
    baselineOnMigrate: true
    locations: classpath:db/migration
